#!/usr/bin/env python3
"""P5C Wave 1 — Synthetic Company Generator (stdlib only).

Generates deterministic synthetic financial-company JSON fixtures that exercise
specific edge cases (holding segment conflicts, IAS-29 anomalies, NIM jumps,
FX shocks, conflicting disclosures, missing metrics, leverage stress, etc.).

Usage:
    python3 scripts/synth_generator.py --case <case_id|all> [--seed N] [--out-dir DIR]

Exit codes:
    0  success
    2  bad arguments
    3  generation error

Constraints:
    - Python stdlib ONLY. No requests/httpx/numpy/pandas. No python-services
      imports. Self-contained CLI.
    - Deterministic: identical (case_id, seed) → identical JSON (modulo
      generated_at timestamp).
    - Output JSON conforms to evals/synthetic/schema/synthetic_company.schema.json.
    - Every fixture sets synthetic_fixture: true and includes a _warning
      field clearly marking the file as non-authoritative test data.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

SCRIPT_VERSION = "1.0.0"

WARNING_TEXT = (
    "SYNTHETIC TEST FIXTURE — NOT REAL FINANCIAL DATA. Auto-generated by "
    "scripts/synth_generator.py for edge-case testing. Do not cite, do not "
    "use for production scoring, do not share externally."
)

CASE_IDS = [
    "holding_with_segment_conflict",
    "airline_missing_da",
    "steel_ias29_anomaly",
    "bank_nim_jump",
    "exporter_fx_shock",
    "conflicting_disclosures",
    "missing_critical_metric",
    "high_leverage_liquidity_stress",
]


# ---------------------------------------------------------------------------
# Per-case generators
# ---------------------------------------------------------------------------

def _gen_holding_with_segment_conflict(rng: random.Random) -> dict[str, Any]:
    revenue = 100000 + rng.randint(-2000, 2000)
    seg_a = 30000 + rng.randint(-500, 500)
    seg_b = 50000 + rng.randint(-500, 500)
    # Segments deliberately sum to less than consolidated revenue.
    return {
        "sector": "holding",
        "induced_issues": ["parent_consolidated_mismatch", "segment_total_mismatch"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {
                    "revenue": revenue,
                    "ebitda": 25000,
                    "net_income": 12000,
                },
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 500000, "total_equity": 200000, "net_debt": 80000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 18000, "depreciation": 5000},
            },
            "segment_breakdown": {
                "fy2025": [
                    {"segment": "energy", "revenue": seg_a, "operating_income": 9000},
                    {"segment": "industrial", "revenue": seg_b, "operating_income": 8000},
                ],
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "segment_reporting",
                "text": (
                    f"Segment toplamı (~{seg_a + seg_b:,} TL) konsolide gelirden "
                    f"(~{revenue:,} TL) düşüktür; eliminasyon notu eksiktir."
                ),
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["segment_total_mismatch", "missing_elimination_note"],
            "should_not_silently_pass": ["segment_total_mismatch"],
            "expected_contradiction_severity": "material",
        },
    }


def _gen_airline_missing_da(rng: random.Random) -> dict[str, Any]:
    revenue = 200000 + rng.randint(-3000, 3000)
    # Induced inversion: ebitda < ebit, which is impossible by definition.
    ebit = 15000
    ebitda = 12000
    return {
        "sector": "aviation",
        "induced_issues": ["depreciation_null_in_cf", "ebitda_lower_than_ebit"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {
                    "revenue": revenue,
                    "ebit": ebit,
                    "ebitda": ebitda,
                    "net_income": 8000,
                },
            },
            "cash_flow": {
                "fy2025": {"cfo": 10000, "depreciation": None, "capex": -25000},
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 350000, "fleet_value": 250000, "net_debt": 180000},
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "fleet_depreciation",
                "text": "Filo amortismanı dipnot 18'de açıklanmıştır; ancak nakit akış tablosunda satır boş bırakılmıştır.",
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["ebitda_lower_than_ebit_inversion", "cf_depreciation_null"],
            "should_not_silently_pass": ["ebitda_lower_than_ebit_inversion"],
            "expected_contradiction_severity": "critical",
        },
    }


def _gen_steel_ias29_anomaly(rng: random.Random) -> dict[str, Any]:
    net_income = 20000 + rng.randint(-500, 500)
    monetary_gain = int(net_income * 0.50)
    operating_profit = 5000  # very low compared to NI dominated by monetary gain
    return {
        "sector": "steel",
        "induced_issues": ["monetary_gain_50pct_of_ni", "operating_margin_anomaly"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {
                    "revenue": 80000,
                    "operating_profit": operating_profit,
                    "monetary_gain": monetary_gain,
                    "net_income": net_income,
                },
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 200000, "total_equity": 90000, "net_debt": 50000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 6000, "depreciation": 8000},
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "ias29_application",
                "text": (
                    f"IAS-29 enflasyon muhasebesi uygulanmıştır; net dönem karının "
                    f"yaklaşık %50'si parasal kazançtan ({monetary_gain:,} TL) kaynaklanmaktadır."
                ),
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["ias29_monetary_gain_dominant", "low_operating_margin_high_NI"],
            "should_not_silently_pass": ["ias29_monetary_gain_dominant"],
            "expected_contradiction_severity": "material",
        },
    }


def _gen_bank_nim_jump(rng: random.Random) -> dict[str, Any]:
    nim_2024 = 0.040
    nim_2025 = 0.080  # YoY doubled
    trading_gain = 15000 + rng.randint(-200, 200)
    return {
        "sector": "banking",
        "induced_issues": ["nim_yoy_doubled", "unexplained_trading_gain"],
        "financial_statements": {
            "income_statement": {
                "fy2024": {"net_interest_income": 40000, "trading_gain": 2000, "net_income": 25000},
                "fy2025": {"net_interest_income": 80000, "trading_gain": trading_gain, "net_income": 50000},
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 1000000, "loans": 700000, "deposits": 800000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 60000},
            },
            "ratios": {"nim_fy2024": nim_2024, "nim_fy2025": nim_2025},
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "nim_increase",
                "text": "Net faiz marjı 2025'te 2024'e göre belirgin artış göstermiştir; metodoloji açıklaması paylaşılmamıştır.",
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["nim_jump_yoy", "trading_gain_unexplained"],
            "should_not_silently_pass": ["nim_jump_yoy"],
            "expected_contradiction_severity": "material",
        },
    }


def _gen_exporter_fx_shock(rng: random.Random) -> dict[str, Any]:
    net_income = 100000 + rng.randint(-1000, 1000)
    fx_translation_gain = int(net_income * 0.40)
    export_revenue_yoy_pct = -0.15
    return {
        "sector": "industrial",
        "induced_issues": ["fx_translation_gain_40pct", "export_revenue_down_despite_try_weakness"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {
                    "revenue": 600000,
                    "export_revenue": 200000,
                    "fx_translation_gain": fx_translation_gain,
                    "net_income": net_income,
                },
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 800000, "total_equity": 300000, "net_debt": 200000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 70000, "depreciation": 30000},
            },
            "ratios": {"export_revenue_yoy_pct": export_revenue_yoy_pct},
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "fx_exposure",
                "text": (
                    f"FX çevrim kazancı net dönem karının yaklaşık %40'ını oluşturmaktadır "
                    f"(~{fx_translation_gain:,} TL). İhracat geliri TL zayıflığına rağmen %15 azaldı."
                ),
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["fx_dominated_earnings", "export_revenue_inconsistency_with_fx"],
            "should_not_silently_pass": ["fx_dominated_earnings"],
            "expected_contradiction_severity": "material",
        },
    }


def _gen_conflicting_disclosures(rng: random.Random) -> dict[str, Any]:
    revenue_main = 150000 + rng.randint(-1000, 1000)
    revenue_alt = revenue_main + 25000  # Conflicting claim
    return {
        "sector": "any",
        "induced_issues": ["disclosure_1_says_X", "disclosure_2_says_Y_on_same_metric"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {"revenue": revenue_main, "ebitda": 30000, "net_income": 18000},
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 400000, "total_equity": 180000, "net_debt": 60000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 24000, "depreciation": 10000},
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "annual_revenue_main_section",
                "text": f"Yıllık gelir {revenue_main:,} TL olarak rapor edilmiştir.",
            },
            {
                "disclosure_id": "DISC_002",
                "topic": "annual_revenue_management_letter",
                "text": f"Yönetim mektubunda yıllık gelir {revenue_alt:,} TL olarak belirtilmiştir.",
                "intentionally_conflicting_with": "DISC_001",
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["critical_contradiction_between_disclosures"],
            "should_not_silently_pass": ["critical_contradiction_between_disclosures"],
            "expected_contradiction_severity": "critical",
        },
    }


def _gen_missing_critical_metric(rng: random.Random) -> dict[str, Any]:
    revenue = 100000 + rng.randint(-2000, 2000)
    return {
        "sector": "industrial",
        "induced_issues": ["revenue_present_ebitda_missing", "coverage_gap_critical"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {
                    "revenue": revenue,
                    "ebitda": None,  # missing critical metric
                    "net_income": None,
                },
            },
            "balance_sheet": {
                "fy2025": {"total_assets": 350000, "total_equity": 150000},
            },
            "cash_flow": {
                "fy2025": {"cfo": 20000},
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "ebitda_omission",
                "text": "FAVÖK satırı bu raporda açıklanmamıştır; analist bu durumda kapsam boşluğu işaretlemelidir.",
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["missing_ebitda", "coverage_gap_at_critical_stem"],
            "should_not_silently_pass": ["missing_ebitda"],
            "expected_contradiction_severity": "material",
        },
    }


def _gen_high_leverage_liquidity_stress(rng: random.Random) -> dict[str, Any]:
    net_debt = 300000 + rng.randint(-2000, 2000)
    ebitda = 50000  # → net_debt/ebitda ≈ 6.0 (above 5 threshold)
    current_assets = 80000
    current_liabilities = 100000  # current_ratio = 0.8 (below 1.0)
    return {
        "sector": "industrial",
        "induced_issues": ["net_debt_to_ebitda_above_5", "current_ratio_below_1"],
        "financial_statements": {
            "income_statement": {
                "fy2025": {"revenue": 250000, "ebitda": ebitda, "net_income": 5000},
            },
            "balance_sheet": {
                "fy2025": {
                    "total_assets": 500000,
                    "total_equity": 60000,
                    "net_debt": net_debt,
                    "current_assets": current_assets,
                    "current_liabilities": current_liabilities,
                },
            },
            "cash_flow": {
                "fy2025": {"cfo": 10000, "depreciation": 25000},
            },
            "ratios": {
                "net_debt_to_ebitda_fy2025": round(net_debt / ebitda, 2),
                "current_ratio_fy2025": round(current_assets / current_liabilities, 2),
            },
        },
        "disclosures": [
            {
                "disclosure_id": "DISC_001",
                "topic": "leverage_disclosure",
                "text": (
                    f"Net borç / FAVÖK çarpanı ~{net_debt/ebitda:.2f}x; cari oran "
                    f"~{current_assets/current_liabilities:.2f}x. Yönetim refinansman planı henüz açıklanmadı."
                ),
            },
        ],
        "expected_agent_behavior": {
            "should_flag": ["leverage_distress", "liquidity_distress", "p0_chairman_question"],
            "should_not_silently_pass": ["leverage_distress", "liquidity_distress"],
            "expected_contradiction_severity": "material",
        },
    }


GENERATORS: dict[str, Callable[[random.Random], dict[str, Any]]] = {
    "holding_with_segment_conflict": _gen_holding_with_segment_conflict,
    "airline_missing_da": _gen_airline_missing_da,
    "steel_ias29_anomaly": _gen_steel_ias29_anomaly,
    "bank_nim_jump": _gen_bank_nim_jump,
    "exporter_fx_shock": _gen_exporter_fx_shock,
    "conflicting_disclosures": _gen_conflicting_disclosures,
    "missing_critical_metric": _gen_missing_critical_metric,
    "high_leverage_liquidity_stress": _gen_high_leverage_liquidity_stress,
}


# ---------------------------------------------------------------------------
# Wrapper that adds the schema-mandated envelope fields
# ---------------------------------------------------------------------------

def generate_company(case_id: str, seed: int) -> dict[str, Any]:
    if case_id not in GENERATORS:
        raise ValueError(f"Unknown case_id: {case_id}")
    rng = random.Random(seed)
    inner = GENERATORS[case_id](rng)
    return {
        "_warning": WARNING_TEXT,
        "synthetic_fixture": True,
        "synthetic_id": f"SYNTH_{case_id.upper()}",
        "case_id": case_id,
        "sector": inner["sector"],
        "induced_issues": inner["induced_issues"],
        "financial_statements": inner["financial_statements"],
        "disclosures": inner["disclosures"],
        "expected_agent_behavior": inner["expected_agent_behavior"],
        "generator": {
            "script_version": SCRIPT_VERSION,
            "seed": seed,
            "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _write(out_path: Path, payload: dict[str, Any]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="synth_generator.py",
        description=(
            "P5C synthetic company generator. Stdlib-only. Deterministic with "
            "--seed. Produces JSON fixtures that conform to "
            "evals/synthetic/schema/synthetic_company.schema.json."
        ),
    )
    parser.add_argument(
        "--case",
        required=True,
        help="Case id from the registry, or 'all' to generate every case.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="RNG seed for deterministic output (default 42).",
    )
    parser.add_argument(
        "--out-dir",
        default="evals/synthetic",
        help="Output directory for JSON fixtures (default evals/synthetic).",
    )

    try:
        args = parser.parse_args(argv)
    except SystemExit as exit_:
        # argparse prints its own error; map invalid argv to exit 2.
        return 2 if exit_.code != 0 else 0

    targets: list[str]
    if args.case == "all":
        targets = list(CASE_IDS)
    elif args.case in CASE_IDS:
        targets = [args.case]
    else:
        sys.stderr.write(
            f"[synth_generator] Unknown --case '{args.case}'. "
            f"Valid: {', '.join(CASE_IDS + ['all'])}\n"
        )
        return 2

    out_dir = Path(args.out_dir)

    for case_id in targets:
        try:
            payload = generate_company(case_id, args.seed)
        except Exception as exc:  # noqa: BLE001 — boundary
            sys.stderr.write(f"[synth_generator] Generation failed for {case_id}: {exc}\n")
            return 3
        out_path = out_dir / f"{case_id}.json"
        try:
            _write(out_path, payload)
        except OSError as exc:
            sys.stderr.write(f"[synth_generator] Write failed for {out_path}: {exc}\n")
            return 3
        sys.stdout.write(f"[synth_generator] wrote {out_path}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
